development:
  adapter: postgresql
  encoding: unicode
  database: uts-kpl
  pool: 5
  host: 'localhost'
  username: postgres  
  password: 123

test:
  adapter: postgresql
  encoding: unicode
  database: sharkapp_test
  pool: 5
  host: 'localhost'
  username: postgres  
  password: 123

production:
  adapter: postgresql
  encoding: unicode
  database: sharkapp_production
  pool: 5
  username: postgres  
  password: 123